sudo: required

language: php
php:
- '7.1.9'

branches:
  only:
  - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
  - ZIP_FILE="php-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"

  # travis-ci secure doc : https://docs.travis-ci.com/user/encryption-keys/
  # before install travis , first install ruby & gem
  # $ gem install travis
  # $ travis encrypt SOMEVAR="secretvalue"

  # AWS_ACCESS_KEY_ID_DEV
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_DEV
  - secure: ""
  # AWS_ACCESS_KEY_ID_STG
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_STG
  - secure: ""
  # AWS_ACCESS_KEY_ID_PROD , value : AKI....QMQ
  - secure: "u14J8Ng1GR9Ga+E32aF4QCyZVnxp8iQGSPElLHSQ1GCHwV8aB7fdpbuIxcuZ98+DXH04QljNu72SMPDSDFZZ0sy/Q2aa1FHmv6GSN1dfD+GZ/vKfGDzoKdw/6YJ+dRToL1N5hra21BA8+acyEOjP0IfLOaX4p2rnN3vjNvG7CpRobu3SHThy79us1JMhE8CFmfiUs5D03pMDOEVVC3rqAh2MAlgKHIsiZfwMlap+2bBsdxe+2gyoEzezIX11ZYfaaemvEJsOexD9VCTJ2dMUoxv1wP56qqPle3IWrT5FOaBxL2NStgqu+hj42YhH8LjA0wEYVoKw6h9kcxsKoDK8Dvi9ifrSRwRUfkDJ6C9W4YcsSE0KYWcaTbEJlQAJWdG4UTHdc5n/yGRYuqYG/+Z1692hJmcr86XAoE9p/NQwo7iIWylfDr7Be8Sb6m8/d0j6Ugc0TZ6JH7ZSPXnRW0P8rALume6JJ7CA4SIrFb3Jc/9Cz3BX8xczmvB1juOOZwxcxmX6OuQQS0zz0dQ4DcTLJrqlMQ/NUY0MujaJMog8LE0o9ISSjDjG2ml7rXssC+BRTjsfFU8PBr39P9h6HXKsTYfs8zJOBz32vUtdfd/jyi8Q1wfOQe6Qkt6Srn5+bx8gQovOzDJ/C0COVb5OmVzbpd6KBzmdElhT6Hm/H39Q/n4="
  # AWS_SECRET_ACCESS_KEY_PROD
  - secure: "hACDocTfu9KrUnlB6sJkWN2d9hA/f7T1YN0OFg5C8qM0o9I/ms7Sd6mSkKJQY5ryD5RBnm+pKR5YP2z8T3GgGvMVjQmM7q65h62mfmccoqsZeb1E3TTLBGItCTbXxYFJaQ8BGkVk5CgXmWcTyCIkDU7ciBah8kyWLCNkBBTZlrScGXQAWdCFmqr0UYkDyQ5rH18eLrWQJnbKLnJeloiohSKI96VA2MhuWqpEEphdmZweoanw0EsOF7ifczEdGrjaoBvFuGUq/Jo+eSWJyMe+7K0C/xP5o2c9302thpiOsxTH9E5yot8YJ/4oM+ESm8etOFpF7YMNlnuQ373klo+JBH7kVRYMh/Nn34ByNzf94kpZPh7pRuKAoQDl+v6GIIgI8/n0t+MMMUrQJ6cIiE9fwo8wdwPH8u5C/qkHOM8KRCzcTgkDwdNb/Qv6JwGnWTA33lowbsKhhXNbrvc7+BJKEk3x7A+u2CoNRsqqp/eq7vAkd3oGdYFck7D/AQC65Ezr61vp8t4LQRLguD5Olrl4283cS/yVJiAPceepd2db97sT+rVbXRzeHGOojwfM2/Rl5MAOjpt40EcYPnDj+XDXohqOqlvYz+bx6cA8RA+RLhv0pUMmGrGvq8ABBUOxaHSkx1uz987NH4z9L8NCyNzfNsSARgyG7ej2F1YfZZ8KgLI="

  # global variables
  - AWS_ACCESS_KEY_ID=''
  - AWS_SECRET_ACCESS_KEY=''
  - AWS_REGION='ap-northeast-1'
  - CODEDEPLOY_APP_NAME=''
  - CODEDEPLOY_GROUP=''


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
# integration to slack , setup on slack travis-ci app
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    rooms:
    - secure: "R+jnOc6oCV6gOqqZWklF+sHBIgejOE1Z+BV/lmirX4RP8An/oST1v32FUSWAfGbd/nIWUqTpZQNOseSROZtYtpWVCyRJU7Td049LyRWdEvHaRlJgxO19ESzYZvkGjVvCXTGKaRmgSq3aZlEBhx9LMXY6ltlFx0k3gbS1o0IvbQFzF1+Y+jl9JQREosT/T41KEGAgvhkZzbZIqpWGgtwd17qXfs1tPIkq6kamsTTHLIYUmWPASsouGHJvinRjaFcRa8yzGQGfoAgSP06N4ITc6Sugf/AgS0s2latPljtgxybhHfWkjpGhawwtGw0QDzZ7fEaAFQKgevPKoqUn5OibUG1nJI7AurSPpDFbwXjjABcAqVyoZU+m9RrgalgdFnltXSy/ycvrXTMAhtM6Yrf3tnweYXKcOfXmZdGVklwXFx8VGDi71XxypBhvaZMjH9PY8rlSBlkA1XkaF1R2VEgI28KetzbX/pfaTM7Colmd7TfiuZ2w/pTjDfP7qy4eYwUFfkXv1s54+yslCncOx5OQuwEjNKx0tanPOwl7ro9XfcoUxKDIx5mRUjeK6YH6Y5t4/nLJIUJFGT7SbiOXuClVRkJyntXz4ChFEnKnAsRZgoBMVSm1qCpwLR+ic93Z/vzLWNNUxARbOlaRNHmHP9fr0vSjOoip3a/2m13WT+iS0Mg="

cache:
  directories:
  - $COMPOSER_CACHE_DIR
  - $HOME/.composer/cache




# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
- set -e
- echo `date +"%Y-%m-%d %H:%M:%S"`
- echo $TRAVIS_BRANCH
- if [[ $TRAVIS_BRANCH == "dev" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "staging" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "master" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD;
    S3_BUCKET='cf-templates-1nws5fs1cm2fm-ap-northeast-1';
    CODEDEPLOY_APP='a1-EC2-CodeDeploy';
    CODEDEPLOY_GROUP='ec2';
  fi


# put testing scripts here
script:
- echo 'script step...'

before_deploy:
- cd "$TRAVIS_BUILD_DIR";
  mkdir "$TRAVIS_BUILD_DIR/zip";
  zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
- provider: S3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  local_dir: $TRAVIS_BUILD_DIR/zip
  bucket: $S3_BUCKET
  skip_cleanup: true
  on:
    all_branches: true

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: $S3_BUCKET
  key: $ZIP_FILE
  bundle_type: zip
  application: $CODEDEPLOY_APP
  deployment_group: $CODEDEPLOY_GROUP
  wait_until_deployed: true
  on:
    all_branches: true
